# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Brian Kimmel (he/him)
title: Associate Director of Software Development
email: kimmelb@gmail.com
website: briankimmel.net
# website_title: Web (Website title override)

# Blog posts section configuration
blog_posts_section:
  layout: left
  title: "Latest Blog Posts"
  data_file: "blog-posts"
  

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: brianrkimmel
stackoverflow_username: "2831"
github_username:  thebesthuman

# Additional icon links
additional_links:
- title: gitlab
  icon: fa fa-gitlab
  url: https://gitlab.com/users/TheBestHuman/projects
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, I'm Brian! I’m an accomplished Engineering Manager with over 20 years of software development experience, leading innovative software teams and projects. I specialize in cloud migrations, agile transformations, and delivering robust C#/.NET/React/Angular/SQL solutions in fast-paced environments. I'm passionate about mentorship and building high-performing teams to drive impactful results.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: IQVIA
        sub_title: Associate Director, Software Development
        caption: June 2019 - Present
        link: https://www.iqvia.com/
        quote: >
          Currently leading a team of 20 software engineers, including 5 direct reports, one of whom is a manager overseeing a team of 4 engineers. Our team develops features for and supports an industry-leading, client-facing, multi-tenant cloud-based SaaS product used by top pharma to plan clinical trials.
        description: | # this will include new lines to allow paragraphs
          
          Began <mark>managing</mark> a team of 4 direct reports in July 2021. Designed and established a comprehensive <mark>hiring</mark> process, optimized for finding great talent in a fair and empathic way. Successfully hired and onboarded 5 additional exceptionally skilled engineers, including a new manager. Mentored and fostered technical skills across the team, with a special focus on coaching the new manager to effectively lead their team.
          

          Orchestrated and executed the migration of our 15-year-old application from our on-premises data center to <mark>Azure</mark>. The <mark>architecture</mark> leveraged Azure SQL Managed Instances, Virtual Machines, Azure Data Factory, Azure DevOps, and Application Gateways with WAF for a robust and secure cloud solution.
          
          
          Designed and managed the adoption of a lightweight <mark>quarterly planning process</mark>, leading to the <mark>on-time delivery</mark> of all releases over the course of four years, enhancing the reliability and efficiency of the engineering teams.
      - layout: left
        title: IQVIA
        sub_title: Lead Software Engineer
        caption: April 2016 – June 2019
        link: https://www.iqvia.com/
        quote: >
          Oversaw design, architecture, and planning for the Clinical Trial Optimization Solutions group 
        description: | # this will include new lines to allow paragraphs
          
          Led a strategic, phased migration of a 15-year-old flagship .NET 3.5 Application to ASP.NET MVC 5 and Angular. This approach enables continuous delivery to production, significantly <mark>enhancing performance, reducing technical debt, and modernizing the user experience</mark>.

          Pioneered and implemented <mark>Scrum</mark> in a previously waterfall environment, establishing buy-in from management and developers unfamiliar with the process. 

          Developed the team’s <mark>Continuous Integration</mark> process and <mark>branching strategy</mark>. Moved the team to <makr>git + Jira + Hudson</mark>, allowing us to test earlier and more often.

  - title: Personal Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: BeadMap
        link: https://gitlab.com/TheBestHuman/beadmap
        link_text: BeadMap
        additional_links:
          - title:  BeadMap on GitLab
            icon: fa fa-gitlab
            url: https://gitlab.com/TheBestHuman/beadmap
        quote: >
          An app written in Node.js/Javascript that converts an image into plans to recreate that image with [Perler beads](https://en.wikipedia.org/wiki/Fuse_beads)
        description: | # this will include new lines to allow paragraphs
          Perler/fuse beads are the perfect Saturday afternoon activity. I was first introduced to them a few years ago and was disappointed with the limited choice of patterns available. I built this as a hobby project to convert arbitrary images into Perler bead patterns.
          This project runs <mark>Node.js</mark> in <mark>Docker</mark> containers with <mark>Javascript</mark> for the UI. It pixelates the image, quantizes the colors, and reconstructs the image in mosaic form, with a helpful legend/shopping list of beads required to reconstruct the image.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Southern Connecticut State University, New Haven, CT
        sub_title: Bachelor of Science in Computer Science
        caption: May 2003
        quote: >
          (Minors: Physics and Mathematics)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
